services:
  postgres:
    image: postgres:16
    hostname: postgres
    container_name: postgres_c
    user: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydatabase #docker exec -it postgres_c psql -U admin -d mydatabase commands are \dt \du \l
    ports:
      - "5432:5432"
    volumes:
      - postgres_dat:/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
      interval: 30s
      timeout: 10s
      retries: 5
  
  pgadmin:
    image: dpage/pgadmin4:9.8
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: jegan@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - postgres
    volumes:
      - myLocal:/data

volumes:
  postgres_dat:
    driver: local
  myLocal: 